### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Baichenjia** [imdarkie/Chinese-novel-generation#3]
发现在 get_init_cell 中，应该将cell的定义修改如下：
def make_cell():
        cell = tf.contrib.rnn.BasicLSTMCell(rnn_size)
        if keep_prob < 1:
            cell = tf.contrib.rnn.DropoutWrapper(cell, output_keep_prob=keep_prob)
        return cell

    cell = tf.contrib.rnn.MultiRNNCell([make_cell() for _ in range(num_layers)])

**Comment by xellimoo** [comment]
对，当时是1.0的时候，现在的定义方式已经改变。不好意思个人原因现在才回复，这个脚本还有很大的改进空间，如果你训练的结果有了实质的产出，请麻烦告知我一下，谢谢！：D
